version: "3.6"

services:
  cloudflared:
    container_name: cloudflared
    restart: unless-stopped
    image: cloudflare/cloudflared:2021.9.2
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        delay: 30s    
      placement:
        constraints: [node.role == manager]
    ports:
      - "5053:5053/udp"
      - "49312:49312/tcp"
    environment:
      - "TUNNEL_DNS_UPSTREAM=https://oiqflrd4jk.cloudflare-gateway.com/dns-query"
    volumes: 
      - /Your/Volume/SwarmS/Cloudflared:/root/.cloudflared
    networks:
      swarmpit_net:
        ipv4_address: 10.0.1.254

  pihole:
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8182:80/tcp"
    environment:
      - "TZ=America/Denver"
      - "DNS1=10.0.1.254#5053"
      - "DNS2=no"
      - "DNSMASQ_LISTENING=all"

    volumes:
      - '/Your/Volume/SwarmS/pihole/etc-pihole/:/etc/pihole/'
      - '/Your/Volume/SwarmS/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
      - '/Your/Volume/SwarmS/pihole/var-log/pihole.log:/var/log/pihole.log'
    networks:
      swarmpit_net:
        ipv4_address: 10.0.1.253
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    
  speedtest:
      container_name: speedtest
      image: henrywhitaker3/speedtest-tracker:latest
      ports:
          - 8765:80
      volumes:
          - /Your/Volume/SwarmS/speedtest:/config
      environment:
          - TZ= 'America/YOUR_TZ'
          - PGID= 1000
          - PUID= 1000
          - OOKLA_EULA_GDPR=true
      logging:
          driver: "json-file"
          options:
              max-file: "10"
              max-size: "200k"
      restart: unless-stopped
networks:
  swarmpit_net:
    external:
      name: swarmpit_net
