######################################################
#                Chart Collections                   #
######################################################
templates:
  Chart:
    sort_title: +1_<<num>><<collection_name>>
    sync_mode: sync
    smart_label: random
  Best of:
    trakt_list: https://trakt.tv/users/lish408/lists/rotten-tomatoes-best-of-<<year>>
    sort_title: +1_Best of <<year>>
    sync_mode: sync
    summary: Rotten Tomatoes Best Movies of <<year>>
    smart_label: audience_rating.desc
#####################################
#    Custom Collection Templates    #
#####################################
  Holiday:
    url_poster: <<poster>>
    sort_title: +++++++_<<collection_name>>
    collection_order: release
#####################################
#     Custom Collection Templates   #
#####################################
  Director:
    sort_title: "!A <<collection_name>>"
    tmdb_director_details: <<tmdb>>
    collection_order: release
    collection_mode: hide
    schedule: weekly(sunday)
  Studio:
    sort_title: "!B <<collection_name>>"
    collection_mode: hide
    schedule: daily
  Special Genre:
    sort_title: "!C <<collection_name>>"
    collection_order: alpha
    collection_mode: hide
  Movies:
    optional:
      - collection
      - tmdb_movie
      - trakt_list
      - tmdb_list
    trakt_list_details: <<trakt_list>>
    tmdb_collection_details: <<collection>>
    tmdb_movie: <<tmdb_movie>>
    tmdb_list: <<tmdb_list>>
    sort_title: <<collection_name>>
    collection_order: release
    collection_mode: hide
#####################################
# End Of Template Start Collections #
#####################################
collections:
  Plex Popular:
    template: { name: Chart, num: 1 }
    tautulli_popular:
      list_days: 30
      list_size: 20
      list_buffer: 20
    tautulli_watched:
      list_days: 30
      list_size: 20
      list_buffer: 20
    summary: Movies Popular on Plex
  Trending:
    template: { name: Chart, num: 2 }
    trakt_trending: 10
    tmdb_trending_daily: 10
    tmdb_trending_weekly: 10
    summary: Movies Trending across the internet
  Popular:
    template: { name: Chart, num: 3 }
    tmdb_popular: 40
    imdb_list:
      url: https://www.imdb.com/search/title/?title_type=feature,tv_movie
      limit: 40
    summary: Popular Movies across the internet
  Top Rated:
    template: { name: Chart, num: 4 }
    imdb_list: https://www.imdb.com/search/title/?groups=top_250&count=250/
    tmdb_top_rated: 250
    summary: Top Rated Movies across the internet
  Best of 2019:
    template: { name: Best of, year: 2019 }
  Best of 2020:
    template: { name: Best of, year: 2020 }
  Best of 2021:
    template: { name: Best of, year: 2021 }
#####################################
#        Holiday Collections        #
#####################################
#  Christmas:
#    template: {name: Holiday, poster: https://theposterdb.com/api/assets/111696}
#    trakt_list:
#      - https://trakt.tv/users/movistapp/lists/christmas-movies
#      - https://trakt.tv/users/2borno2b/lists/christmas-movies-extravanganza
#      - https://trakt.tv/users/pualani78/lists/christmas-2020
#      - https://trakt.tv/users/veninjak/lists/complete-christmas-2021-copy
#    imdb_list:
#      - https://www.imdb.com/list/ls025976544/
#      - https://www.imdb.com/list/ls003863000/
#      - https://www.imdb.com/list/ls027454200/
#      - https://www.imdb.com/list/ls027886673/
#      - https://www.imdb.com/list/ls097998599/
#    summary: Christmas film is a genre that revolves around the plot involving Christmas.
#####################################
#        Director Collections       #
######################################
  Christopher Nolan:
    template: {name: Director, tmdb: 525}
  Edgar Wright:
    template: {name: Director, tmdb: 11090}
  James Cameron:
    template: {name: Director, tmdb: 2710}
  M. Night Shyamalan:
    template: {name: Director, tmdb: 11614}
  Martin Scorsese:
    template: {name: Director, tmdb: 1032}
  Steven Spielberg:
    template: {name: Director, tmdb: 488}
  Quentin Tarantino:
    template: {name: Director, tmdb: 138}
  Wes Anderson:
    template: {name: Director, tmdb: 5655}
#####################################
#         Studio Collections        #
#####################################
  DC Extended Universe:
    template: {name: Studio}
    imdb_list: https://www.imdb.com/list/ls077827588/
    summary: "The DC Extended Universe (DCEU) is a media franchise and shared universe centered on superheros from DC Comics."
    collection_order: release
  Marvel Studios:
    template: {name: Studio}
    imdb_list: https://www.imdb.com/list/ls009410711/
    summary: "A collection of movies and shows created by Marvel Studios, comprising of the Marvel Cinematic Universe."
    collection_order: release
  Disney Animation:
    template: {name: Studio}
    imdb_list: https://www.imdb.com/search/title/?companies=co0074039&count=250
    summary: A collection of Disney Animation movies.
    content_rating: G
    collection_order: alpha
  Pixar Animation:
    template: {name: Studio}
    imdb_list: https://www.imdb.com/list/ls087911008/
    summary: "A collection of Pixar Animation movies."
    content_rating: G
    collection_order: alpha
#####################################
#      Special Genre Collections    #
#####################################
  Mind Messing Movies:
    template: {name: Special Genre}
    trakt_list: https://trakt.tv/users/hdlists/lists/mindfuck-movies
    summary: "A collection of movies that will mess with your mind!"
  Outer Space & Exploration Movies:
    template: {name: Special Genre}
    trakt_list: https://trakt.tv/users/hdlists/lists/outer-space-space-exploration-movies
    summary: "A collection of movies that feature outer space and exploration."
  Superhero Movies:
    template: {name: Special Genre}
    trakt_list: https://trakt.tv/users/hdlists/lists/superhero-movies-from-1980-to-today
    summary: "A collection of superhero movies released from 1980 until today."
  Time Travel Movies:
    template: {name: Special Genre}
    trakt_list:
      - https://trakt.tv/lists/3940186
      - https://trakt.tv/lists/20709447
      - https://trakt.tv/lists/2729898
      - https://trakt.tv/lists/2729898
      - https://trakt.tv/lists/4297290
      - https://trakt.tv/lists/2652307
    imdb_list:
      - https://www.imdb.com/list/ls068617191/
      - https://www.imdb.com/list/ls004426453/
    summary: "A collection of movies that include time travel."
#####################################
#     General Movies Collections    #
#####################################
  Alien:
    template: {name: Movies, collection: 8091}
  Attack on Titan:
    template: {name: Movies, collection: 383987}
  Back to the Future:
    template: {name: Movies, collection: 264}
  Candyman:
    template: {name: Movies, collection: 98580}
  The Dark Knight:
    template: {name: Movies, collection: 263}
    sort_title: Dark Knight
  Deadpool:
    template: {name: Movies, collection: 448150}
  Die Hard:
    template: {name: Movies, collection: 1570}
  Fantastic Beasts:
    template: {name: Movies, collection: 435259}
  The Fast and the Furious:
    template: {name: Movies, collection: 9485}
    sort_title: Fast and the Furious
  Final Destination:
    template: {name: Movies, collection: 8864}
  The Godfather:
    template: {name: Movies, collection: 230}
    sort_title: Godfather
  Harry Potter:
    template: {name: Movies, collection: 1241}
  The Hobbit:
    template: {name: Movies, collection: 121938}
    sort_title: Hobbit
  Halloween:
    template: {name: Movies, collection: 91361}
  The Hunger Games:
    template: {name: Movies, collection: 131635}
    sort_title: Hunger Games
  Ice Age:
    template: {name: Movies, collection: 8354}
  Indiana Jones:
    template: {name: Movies, collection: 84}
  James Bond:
    template: {name: Movies, collection: 645}
  John Wick:
    template: {name: Movies, collection: 404609}
  Jurassic Park:
    template: {name: Movies, collection: 328}
  The Karate Kid:
    template: {name: Movies, collection: 8580}
    sort_title: Karate Kid
  The Land Before Time:
    template: {name: Movies, collection: 19163}
    sort_title: Land Before Time
  The Lord of the Rings:
    template: {name: Movies, collection: 119}
    sort_title: Lord of the Rings
  Men in Black:
    template: {name: Movies, collection: 86055}
  Middle Earth:
    template: {name: Movies, collection: "119,121938"}
    summary: A collection of movies and shows set in J.R.R. Tolkien's Middle Earth.
  Mission Impossible:
    template: {name: Movies, collection: 87359}
  Monsterverse:
    imdb_list: https://www.imdb.com/list/ls060980695/
    summary: A collection of all the MonsterVerse movies.
    collection_mode: hide
  The Mummy:
    template: {name: Movies, collection: 1733}
  A Nightmare on Elm Street:
    template: {name: Movies, collection: 8581, tmdb_movie: 23437}
    sort_title: Nightmare on Elm Street
  Pirates of the Caribbean:
    template: {name: Movies, collection: 295}
  Predator:
    template: {name: Movies, collection: 399}
  Rambo:
    template: {name: Movies, collection: 5039}
  Rocky:
    template: {name: Movies, collection: 1575}
  Saw:
    template: {name: Movies, collection: 656}
  Scary Movies:
    template: {name: Movies, collection: 4246}
  Scream:
    template: {name: Movies, collection: 2602}
  Sharknado:
    template: {name: Movies, collection: 286023}
  Shrek:
    template: {name: Movies, collection: 2150}
  Spider-Man:
    template: {name: Movies, collection: "556,125574,531241,573436"}
    summary: A collection of all the mainstream Spider-Man movies.
  Star Trek:
    template: {name: Movies, collection: "151,115575,115570"}
    summary: "Star Trek is an American science fiction media franchise originating from the 1960s television series Star Trek, created by Gene Roddenberry."
  Star Wars:
    template: {name: Movies, collection: 10}
  Superman:
    template: {name: Movies, collection: 8537}
  Taken:
    template: {name: Movies, collection: 135483}
  Taxi:
    template: {name: Movies, collection: 211721}
  Terminator:
    template: {name: Movies, collection: 528}
  Transformers:
    template: {name: Movies, collection: 8650}
  The Transporter:
    template: {name: Movies, collection: 9518}
    sort_title: Transporter
  Tremors:
    template: {name: Movies, collection: 91799}
  The Twilight Saga:
    template: {name: Movies, collection: 33514}
    sort_title: Twilight Saga
  Wizarding World:
    template: {name: Movies, collection: "1241,435259"}
    summary: A collection of all the Wizarding World movies, including the Harry Potter and Fantastic Beasts series.
  X-Men:
    template: {name: Movies, collection: "748,453993"}